### ISSUE TITLE
Missing "subscription_updated"

### ISSUE THREAD

**Issue by lassegit** [remorses/lemonsqueezy-webhooks#1]
Lemonsqueezy sends `subscription_updated` events, shouldn't this be added to?

```
Subscription, the payload.data type for the events
subscription_created
subscription_cancelled
subscription_resumed
subscription_expired
subscription_paused
subscription_unpaused

```

**Comment by remorses** [comment]
I must have missed that

**Comment by lassegit** [comment]
@remorses Thanks for the quick response. Did you publish changes to npm? I am not seeing a version 0.0.4 https://www.npmjs.com/package/lemonsqueezy-webhooks?activeTab=readme

**Comment by remorses** [comment]
yes, not sure why you can't see it

**Comment by lassegit** [comment]
Now I see it. Thanks.
