### ISSUE TITLE
missing `customer_id`

### ISSUE THREAD

**Issue by waptik** [remorses/lemonsqueezy-webhooks#2]
The `customer_id`attributes seems to be missing for the `Subscription` type

Ref: https://docs.lemonsqueezy.com/api/subscriptions#the-subscription-object

**Comment by remorses** [comment]
This must be a new field, will add later

**Comment by waptik** [comment]
> This must be a new field, will add later

I see. I manually fixed it by doing
```
const data = payload.data as (typeof payload)["data"] & { attributes: { customer_id: number } };
```

**Comment by remorses** [comment]
Fixed in latest versino

**Comment by remorses** [comment]
Fixed in latest version

**Comment by waptik** [comment]
thanks
